[package]
name = "tower-sessions-file-based-store"
description = "File-based session store for `tower-sessions`."
authors = ["Max Katz <max.katz@gmail.com>"]
license = "MIT"
homepage = "https://github.com/maxk42/tower-sessions-file-store"
repository = "https://github.com/maxk42/tower-sessions-file-store"
keywords = ["axum", "sessions", "tower", "file", "tower-sessions"]
categories = ["asynchronous", "network-programming", "web-programming"]
version = "0.1.3"
edition = "2021"
readme = "README.md"


[dependencies]
async-trait = "0.1.89"
axum = "0.8.8"
serde_json = "1.0.133"
tower-sessions = "0.15.0"
